# Generated by Django 5.2.8 on 2025-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего заказов'),
        ),
    ]
