# Generated by Django 5.2.8 on 2025-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_no',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер заказа покупателя'),
            preserve_default=False,
        ),
    ]
